### ISSUE TITLE
It is not possible to call AddField when base type is interface

### ISSUE THREAD

**Issue by sfiodorov** [charlesdevandiere/graphql-query-builder-dotnet#10]
Have interface :
```
interface IFoo 
{
    string Value {get;set;}
}
```
Have class 
```
class Foo : IFoo
{
}
```

Extension code:
```
public static IQuery<T> WithValue<T>(this IQuery<T> query)
           where T : class, IFoo
        {
            return query.AddField(x => x.Value);
        }

```
Call : 
 `IQuery<Foo> fields = new Query<Foo>().WithValue()`

Expected : value property should be added to query
Observed: ArgumentException fired from QueryOf{T}.cs
Reason: Foo implements the IFoo and not delivered from it. So call to type.IsSubclassOf at line 229 of  QueryOf{T} is not valid
Solution: replace call to  IsSubclassOf by IsAssignableFrom to allow interface as base type

This PR should fix it: https://github.com/charlesdevandiere/graphql-query-builder-dotnet/pull/9/commits/97eb06286ce40a24a791ae54591ddf612cac6903

@charlesdevandiere , Could you take a look please?

**Comment by sfiodorov** [comment]
@charlesdevandiere , thanks for merging PR. Is it possible to release new nuget version, please?

**Comment by charlesdevandiere** [comment]
@sfiodorov v1.1.3 is now published on NuGet :wink:
Thanks a lot for the PR !
