### ISSUE TITLE
Is there a problem to create a Query with complex objects in Arguments?

### ISSUE THREAD

**Issue by t-henrique** [charlesdevandiere/graphql-query-builder-dotnet#19]
Hi. I'm trying to put and object as param but is throwing an exception when I execute query.Builder(). 

My object is :

```
class Filter {
    int parent;
    int amount;
    List<Clauses> clauses;
}
```
I am trying to create Arguments, but isn't working.

What I've tried:

```
//creating arguments
var arguments = new Dictionary<string, object>();
arguments.Add("filters", new filters { parent = 1, amount = 15 });

var query = new Query<MyType>("MyTypes")
.AddArguments(arguments)[...]
query.Build();
```
Throws InvalidDataException: Unsupported Query Parameter

I've tried this too, but without any success. 

```
var query = new Query<MyType>("MyTypes")
.AddArguments(new {filters, arguments)[...]
query.Build();

```
The same error. How could I create a request using Filter object?

**Comment by t-henrique** [comment]
and I've already tried this without any success:

```
var params = new Filter{ parent = 1, amount = 15 };
.AddArguments(new { filters = params })
```

**Comment by charlesdevandiere** [comment]
Hi @t-henrique.

The `AddArgument`/`AddArguments` methods support only these following types for dictionary value:

- String
- Number
- Boolean
- Enum
- Key value pair
- List
- Dictionary

You must add your arguments like this:

```csharp
.AddArgument("filters", new Dictionary<string, object> { { "parent", 1 }, { "amount", 15 } })
```

**Comment by t-henrique** [comment]
Thank you. Worked fine!

**Comment by richardaubin** [comment]
Can you show an example of a custom arguments type for AddArguments<T>?
