### ISSUE TITLE
Support long as parameter type at QueryStringBuilder

### ISSUE THREAD

**Issue by sfiodorov** [charlesdevandiere/graphql-query-builder-dotnet#2]
Please add support for long at:
QueryStringBuilder:FormatQueryParam

**Comment by charlesdevandiere** [comment]
@sfiodorov thanks for this issue!

I fixed it in v1.1.1!

Tell me if it works for you 😊

**Comment by sfiodorov** [comment]
@charlesdevandiere , thanks.
