### ISSUE TITLE
Mutation Query

### ISSUE THREAD

**Issue by Dharuman007** [charlesdevandiere/graphql-query-builder-dotnet#20]
Hi charles,
            how can send object parameter in C# like entity:{test:"",test1:""}.

Thanks
Dharuman N

**Comment by charlesdevandiere** [comment]
Hi @Dharuman007,
I'm not sure to understend what you want to do but graphql-query-builder only build the query. Use [GraphQL.Client](https://github.com/graphql-dotnet/graphql-client) to send variable.

**Comment by Dharuman007** [comment]
Hi Charles,
                        Please have look at the below query highlighted in red and send me the query in correct format. Please guide how to implement parameters highlighted in red using C#

              query FirstScreenQuery1 {
  workOrders {
    headers {
      getAllPaged(Entiy:{name:"name",notes:"Notes"}) {
        totalCount
        items {
          id


      }
    }
  }
}
}

Thanks
Dharuman

**Comment by charlesdevandiere** [comment]
Hi @Dharuman007,

The text does not appear highlighted in the GitHub interface.

To send `Entiy:{name:"name",notes:"Notes"}` parameters, try this:

```csharp
.AddArgument("entity", new Dictionary<string, object> { { "name", "name" }, { "notes", "notes" } })
```

Currently there is a limitation to use `Dictionary<string, string>`, I'm working on it.

Regards

**Comment by Dharuman007** [comment]
Hi Charles,
                 Thanks for your solution. Its working for me.


Thanks
Dharuman N

**Comment by gopala000** [comment]
One of the service that I consume expect a Json as an argument value. If I pass a Json value, the library throws exception. Is there a workaround?
