### ISSUE TITLE
Query Build with nullable value exception.

### ISSUE THREAD

**Issue by t-henrique** [charlesdevandiere/graphql-query-builder-dotnet#22]
I'm trying to create a mutation query that contains an KeyValue property with possible Null value, following we have an example:

`
Dice.SoldAt is a Nullable<DateTime> that is null at when it is created on api.
new Dictionary<string, DateTime?>
			{
				{"dice_id", Dice.Id},
				{"sold_at", Dice.SoldAt}
...
			};`

And when I try to build my query, I got an null exception. 

This is the exception message.

> Unsupported Query Parameter, Type Found : System.Collections.Generic.KeyValuePair`2[System.String,System.Nullable`1[System.DateTime]]

How to create a query which accepts nullable values?

**Comment by charlesdevandiere** [comment]
Hi @t-henrique, the problem is not with Nullable but with DateTime. I added the DateTime support for query params in the [last release](https://github.com/charlesdevandiere/graphql-query-builder-dotnet/releases/tag/1.4.0) #27.

I hope this will solve your problem.
