### ISSUE TITLE
How to add "sortKey:TITLE" argument

### ISSUE THREAD

**Issue by rcrum-CurePay** [charlesdevandiere/graphql-query-builder-dotnet#23]
I really like this tool, but can't figure out how to add argument "sortKey:TITLE" to use with Shopify's GraphQL.  Anybody?

**Comment by charlesdevandiere** [comment]
Hi, @rcrum-CurePay, you can add this with `.AddArgument("sortKey", SortKeys.TITLE)` (SortKeys is an enum)

I hope this will solve your problème
