### ISSUE TITLE
Formatter usage building the Query Arguments

### ISSUE THREAD

**Issue by VictoriaKalinichenko** [charlesdevandiere/graphql-query-builder-dotnet#34]
Hi, @charlesdevandiere 
First of all, thank you so much, I guess a lot of programming lives were saved thanks to your efforts : )

But I have found a tiny issue with the Argument list building.
The **Formatter** from **Query** is not passed to the **QueryStringBuilder**, so in case if there is an object in the Query Arguments, the Formatter is not applied to the object. 

Can I make a pull request to fix that?

**Comment by charlesdevandiere** [comment]
Hi @VictoriaKalinichenko,
Yes of course, you can make a pull request !
Thank you very much !

**Comment by VictoriaKalinichenko** [comment]
Hi @charlesdevandiere 
Here the [pull request link](https://github.com/charlesdevandiere/graphql-query-builder-dotnet/pull/35), thank you : )

**Comment by charlesdevandiere** [comment]
Thank you @VictoriaKalinichenko !
