### ISSUE TITLE
Missing serializer references?

### ISSUE THREAD

**Issue by SeanAxion** [charlesdevandiere/graphql-query-builder-dotnet#39]
Is this dead? It looks like you need an instance of `IGraphQLWebsocketJsonSerializer` to instantiate `GraphQLHttpClient` but the references lead nowhere.

**Comment by charlesdevandiere** [comment]
Hi @SeanAxion, the project is not dead. GraphQL.Query.Builder is only used for building the graphQL query. To use the client please refer to its [documentation](https://github.com/graphql-dotnet/graphql-client)
