### ISSUE TITLE
Nullable arguments

### ISSUE THREAD

**Issue by boiche** [charlesdevandiere/graphql-query-builder-dotnet#41]
### Description
I need to filter a query based on nullable field. Currently I cannot use the query builder to say : { neq: null } because this triggers compiler error [CS0828](https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0828?f1url=%3FappId%3Droslyn%26k%3Dk(CS0828)). In order to use the null filtration properly, I've to explicitly replace all occurrences of "null" with null. It would be nice if the builder does this task for me.

**Comment by charlesdevandiere** [comment]
Fixed in #44
