### ISSUE TITLE
Update reference on Newtonsoft.Json to v 12.x.y

### ISSUE THREAD

**Issue by reureu** [charlesdevandiere/graphql-query-builder-dotnet#8]
Hi guys,

We are happily using GraphQL.Query.Builder to build our queries.
There one minor problem though: the latest release depends on Newtonsoft.Json 11.0.1.
It would be good to upgrade its dependencies to a more recent release, like 12.0.3.

This would save some hassle with bindingRedirect's in exe.config files, as most of the GraphQL.Server 3.x dependencies are now using Newtonsoft.Json 12.0.3.

Kind regards,
Reureu

**Comment by charlesdevandiere** [comment]
Hi,

I fixed it in [1.2.0](https://github.com/charlesdevandiere/graphql-query-builder-dotnet/releases/tag/1.2.0)

Enjoy
